version: "3"

services:
  bot:
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    build:
      context: "giga_bot"
      dockerfile: Dockerfile
    volumes:
      - "./giga_bot:/giga_bot"
    restart: always